"""users 4

Revision ID: d4b2d7af94ee
Revises: fee8f92f065e
Create Date: 2026-04-07 00:30:35.720655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b2d7af94ee'
down_revision: Union[str, Sequence[str], None] = 'fee8f92f065e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cars', sa.String(), nullable=False))
    op.add_column('users', sa.Column('favorite_stations', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_stations')
    op.drop_column('users', 'cars')
    # ### end Alembic commands ###
